# Generated by Django 4.1.5 on 2023-11-14 09:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.TextField(default='', verbose_name='Заголовок')),
                ('author', models.CharField(default='FAURI', max_length=25, verbose_name='Автор новости')),
                ('image', models.ImageField(default='umolcanie.jpg', upload_to='', verbose_name='Картинка')),
                ('description', models.TextField(default='')),
                ('category', models.CharField(choices=[('событие', 'Событие'), ('тренировка', 'Тренировка'), ('международные соревнования', 'Международные соревнования'), ('соревнования', 'Соревнования')], default='событие', max_length=50, verbose_name='Категория события')),
                ('day', models.DateField(blank=True, null=True, verbose_name='Дата события')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала события')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время конца события ')),
                ('creation_day', models.DateField(default=datetime.date.today, verbose_name='Дата создания ')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная ')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.TextField(default='', verbose_name='Заголовок или описание')),
                ('image', models.ImageField(upload_to='partners_and_slider/', verbose_name='Картинка')),
                ('ssilka', models.TextField(default='', verbose_name='Заголовок или описание')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Pdfs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(blank=True, null=True, verbose_name='Дата проведения')),
                ('bazeinfo', models.TextField(default='', verbose_name='Название')),
                ('category_text', models.CharField(choices=[('Событие', 'Событие'), ('Тренировка', 'Тренировка'), ('Международные соревнования', 'Международные соревнования'), ('Соревнования', 'Соревнования')], default='событие', max_length=50, verbose_name='Категория')),
                ('organizers', models.TextField(blank=True, default='', null=True, verbose_name='Организаторы')),
                ('register', models.TextField(blank=True, help_text='Ссылка', null=True, verbose_name='Регистрация')),
                ('info_text', models.TextField(blank=True, default='', null=True, verbose_name='Бюллетень')),
                ('rezul_text', models.TextField(blank=True, default='', null=True, verbose_name='Результаты')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архив',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header', models.TextField(default='', verbose_name='Заголовок или описание')),
                ('image', models.ImageField(upload_to='partners_and_slider/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Срочное',
                'verbose_name_plural': 'Срочное',
            },
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='файл', upload_to='static/pdf_files/', verbose_name='Файл')),
                ('text_result', models.TextField(blank=True, default='Результаты', null=True, verbose_name='Результаты')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezul_files', to='store.pdfs')),
            ],
            options={
                'verbose_name': 'Результаты',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='InfoFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='файл', upload_to='static/pdf_files/', verbose_name='Файл')),
                ('text_info', models.TextField(blank=True, default='Информация', null=True, verbose_name='Информация')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_files', to='store.pdfs')),
            ],
            options={
                'verbose_name': 'Бюллетень',
                'verbose_name_plural': 'Бюллетень',
            },
        ),
    ]
