# Generated by Django 4.1.5 on 2023-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='ssilka',
            field=models.TextField(default='', verbose_name='Ссылка'),
        ),
    ]
